use utoipa::OpenApi;

use crate::handlers::{
    admin_auth_handler, admin_order_handler, admin_runner_order_handler, auth_handler, cart_handler,
    category_handler, member_handler, order_handler, product_handler, runner_order_handler,
    store_handler,
};
use axum_application::dtos::user_dto::{UserResponse, WechatLoginDto};
use axum_common::response::{self, PagedResponse};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Backend Template API",
        version = "1.0.0",
        description = "Minimal user CRUD example"
    ),
    paths(
        auth_handler::wechat_login,
        admin_auth_handler::admin_login,
        member_handler::member_status,
        member_handler::member_benefits,
        store_handler::nearby_stores,
        cart_handler::get_cart,
        cart_handler::add_item,
        cart_handler::update_qty,
        cart_handler::remove_item,
        cart_handler::clear_cart,
        order_handler::create_order,
        order_handler::pay_order,
        order_handler::list_orders,
        order_handler::get_order,
        order_handler::cancel_order,
        runner_order_handler::create_runner_order,
        runner_order_handler::pay_runner_order,
        runner_order_handler::list_runner_orders,
        runner_order_handler::get_runner_order,
        runner_order_handler::cancel_runner_order,
        admin_order_handler::admin_list_orders,
        admin_order_handler::admin_accept_order,
        admin_order_handler::admin_dispatch_order,
        admin_order_handler::admin_complete_order,
        admin_runner_order_handler::admin_list_runner_orders,
        admin_runner_order_handler::admin_accept_runner_order,
        admin_runner_order_handler::admin_delivered_runner_order,
        admin_runner_order_handler::admin_complete_runner_order,
        category_handler::list_categories,
        product_handler::list_products,
        product_handler::search_products,
    ),
    components(
        schemas(
            WechatLoginDto,
            UserResponse,
            auth_handler::LoginResponse,
            admin_auth_handler::AdminLoginDto,
            admin_auth_handler::AdminResponse,
            admin_auth_handler::AdminLoginResponse,
            member_handler::MemberStatusResponse,
            member_handler::MemberBenefitsResponse,
            store_handler::StoreNearbyResponse,
            cart_handler::AddItemRequest,
            cart_handler::UpdateQtyRequest,
            cart_handler::RemoveItemRequest,
            cart_handler::ClearCartRequest,
            cart_handler::CartItemResponse,
            cart_handler::CartResponse,
            order_handler::OrderItemRequest,
            order_handler::CreateOrderRequest,
            order_handler::PayOrderRequest,
            order_handler::CancelOrderRequest,
            order_handler::OrderItemResponse,
            order_handler::OrderResponse,
            runner_order_handler::CreateRunnerOrderRequest,
            runner_order_handler::PayRunnerOrderRequest,
            runner_order_handler::CancelRunnerOrderRequest,
            runner_order_handler::RunnerOrderResponse,
            admin_order_handler::AdminListOrdersQuery,
            admin_runner_order_handler::AdminListRunnerOrdersQuery,
            category_handler::CategoryResponse,
            product_handler::ProductResponse,
            response::ApiResponse<auth_handler::LoginResponse>,
            response::ApiResponse<admin_auth_handler::AdminLoginResponse>,
            response::ApiResponse<member_handler::MemberStatusResponse>,
            response::ApiResponse<member_handler::MemberBenefitsResponse>,
            response::ApiResponse<Vec<store_handler::StoreNearbyResponse>>,
            response::ApiResponse<cart_handler::CartResponse>,
            response::ApiResponse<order_handler::OrderResponse>,
            response::ApiResponse<Vec<order_handler::OrderResponse>>,
            response::ApiResponse<runner_order_handler::RunnerOrderResponse>,
            response::ApiResponse<Vec<runner_order_handler::RunnerOrderResponse>>,
            response::ApiResponse<Vec<category_handler::CategoryResponse>>,
            response::ApiResponse<PagedResponse<product_handler::ProductResponse>>,
            response::ErrorDetail,
            response::FieldError,
        )
    ),
    tags(
        (name = "Auth", description = "Login and tokens"),
        (name = "Admin", description = "Admin login"),
        (name = "Member", description = "Member status and benefits"),
        (name = "Store", description = "Store browsing"),
        (name = "Cart", description = "Shopping cart"),
        (name = "Order", description = "Goods orders"),
        (name = "RunnerOrder", description = "Runner orders"),
        (name = "AdminOrder", description = "Admin goods orders"),
        (name = "AdminRunnerOrder", description = "Admin runner orders"),
        (name = "Category", description = "Category browsing"),
        (name = "Product", description = "Product browsing"),
        (name = "System", description = "System endpoints")
    )
)]
pub struct ApiDoc;
