use utoipa::OpenApi;

use crate::dtos::{
    address_dto, admin_auth_dto, admin_order_dto, admin_runner_order_dto, auth_dto, cart_dto,
    category_dto, config_dto, member_dto, order_dto, product_dto, runner_order_dto, store_dto,
};
use crate::handlers::{
    address_handler, admin_auth_handler, admin_category_handler, admin_order_handler,
    admin_product_handler, admin_runner_order_handler, admin_store_handler, auth_handler,
    cart_handler, category_handler, config_handler, member_handler, order_handler, product_handler,
    runner_order_handler, store_handler,
};
use axum_common::response::{self, PagedResponse};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Backend Template API",
        version = "1.0.0",
        description = "Minimal user CRUD example"
    ),
    paths(
        auth_handler::wechat_login,
        auth_handler::send_sms_code,
        auth_handler::phone_sms_login,
        config_handler::get_config,
        address_handler::list_addresses,
        address_handler::create_address,
        address_handler::update_address,
        address_handler::delete_address,
        address_handler::set_default_address,
        admin_auth_handler::admin_login,
        admin_store_handler::admin_list_stores,
        admin_store_handler::admin_create_store,
        admin_store_handler::admin_update_store,
        admin_category_handler::admin_create_category,
        admin_category_handler::admin_update_category,
        admin_product_handler::admin_create_product,
        admin_product_handler::admin_update_product,
        member_handler::member_status,
        member_handler::member_benefits,
        store_handler::nearby_stores,
        store_handler::select_store,
        store_handler::current_store,
        cart_handler::get_cart,
        cart_handler::add_item,
        cart_handler::update_qty,
        cart_handler::remove_item,
        cart_handler::clear_cart,
        order_handler::create_order,
        order_handler::preview_order,
        order_handler::pay_order,
        order_handler::list_orders,
        order_handler::get_order,
        order_handler::cancel_order,
        order_handler::repurchase_order,
        runner_order_handler::create_runner_order,
        runner_order_handler::pay_runner_order,
        runner_order_handler::list_runner_orders,
        runner_order_handler::get_runner_order,
        runner_order_handler::cancel_runner_order,
        admin_order_handler::admin_list_orders,
        admin_order_handler::admin_accept_order,
        admin_order_handler::admin_dispatch_order,
        admin_order_handler::admin_complete_order,
        admin_runner_order_handler::admin_list_runner_orders,
        admin_runner_order_handler::admin_accept_runner_order,
        admin_runner_order_handler::admin_delivered_runner_order,
        admin_runner_order_handler::admin_complete_runner_order,
        category_handler::list_categories,
        product_handler::list_products,
        product_handler::search_products,
        product_handler::get_product,
    ),
    components(
        schemas(
            auth_dto::WechatLoginDto,
            auth_dto::SendSmsCodeDto,
            auth_dto::PhoneSmsLoginDto,
            auth_dto::UserResponse,
            auth_dto::LoginResponse,
            auth_dto::SendSmsCodeResponse,
            config_dto::ConfigResponse,
            address_dto::CreateAddressRequest,
            address_dto::UpdateAddressRequest,
            address_dto::AddressResponse,
            admin_auth_dto::AdminLoginDto,
            admin_auth_dto::AdminResponse,
            admin_auth_dto::AdminLoginResponse,
            member_dto::MemberStatusResponse,
            member_dto::MemberBenefitsResponse,
            store_dto::SelectStoreRequest,
            store_dto::AdminCreateStoreRequest,
            store_dto::AdminUpdateStoreRequest,
            store_dto::StoreNearbyResponse,
            store_dto::StoreResponse,
            store_dto::StoreAdminResponse,
            cart_dto::AddItemRequest,
            cart_dto::UpdateQtyRequest,
            cart_dto::RemoveItemRequest,
            cart_dto::ClearCartRequest,
            cart_dto::CartItemResponse,
            cart_dto::CartResponse,
            order_dto::OrderItemRequest,
            order_dto::PreviewOrderRequest,
            order_dto::OrderPreviewResponse,
            order_dto::CreateOrderRequest,
            order_dto::PayOrderRequest,
            order_dto::CancelOrderRequest,
            order_dto::OrderItemResponse,
            order_dto::OrderResponse,
            runner_order_dto::CreateRunnerOrderRequest,
            runner_order_dto::PayRunnerOrderRequest,
            runner_order_dto::CancelRunnerOrderRequest,
            runner_order_dto::RunnerOrderResponse,
            admin_order_dto::AdminListOrdersQuery,
            admin_runner_order_dto::AdminListRunnerOrdersQuery,
            category_dto::CategoryResponse,
            category_dto::AdminCreateCategoryRequest,
            category_dto::AdminUpdateCategoryRequest,
            product_dto::ProductDetailQuery,
            product_dto::AdminCreateProductRequest,
            product_dto::AdminUpdateProductRequest,
            product_dto::ProductResponse,
            response::ApiResponse<auth_dto::LoginResponse>,
            response::ApiResponse<auth_dto::SendSmsCodeResponse>,
            response::ApiResponse<config_dto::ConfigResponse>,
            response::ApiResponse<Vec<address_dto::AddressResponse>>,
            response::ApiResponse<address_dto::AddressResponse>,
            response::ApiResponse<bool>,
            response::ApiResponse<admin_auth_dto::AdminLoginResponse>,
            response::ApiResponse<Vec<store_dto::StoreAdminResponse>>,
            response::ApiResponse<store_dto::StoreAdminResponse>,
            response::ApiResponse<category_dto::CategoryResponse>,
            response::ApiResponse<product_dto::ProductResponse>,
            response::ApiResponse<member_dto::MemberStatusResponse>,
            response::ApiResponse<member_dto::MemberBenefitsResponse>,
            response::ApiResponse<Vec<store_dto::StoreNearbyResponse>>,
            response::ApiResponse<store_dto::StoreResponse>,
            response::ApiResponse<cart_dto::CartResponse>,
            response::ApiResponse<order_dto::OrderPreviewResponse>,
            response::ApiResponse<order_dto::OrderResponse>,
            response::ApiResponse<Vec<order_dto::OrderResponse>>,
            response::ApiResponse<runner_order_dto::RunnerOrderResponse>,
            response::ApiResponse<Vec<runner_order_dto::RunnerOrderResponse>>,
            response::ApiResponse<Vec<category_dto::CategoryResponse>>,
            response::ApiResponse<PagedResponse<product_dto::ProductResponse>>,
            response::ApiResponse<product_dto::ProductResponse>,
            response::ErrorDetail,
            response::FieldError,
        )
    ),
    tags(
        (name = "Auth", description = "Login and tokens"),
        (name = "Config", description = "Global config"),
        (name = "Address", description = "Address management"),
        (name = "Admin", description = "Admin login"),
        (name = "AdminStore", description = "Admin store management"),
        (name = "AdminCategory", description = "Admin category management"),
        (name = "AdminProduct", description = "Admin product management"),
        (name = "Member", description = "Member status and benefits"),
        (name = "Store", description = "Store browsing"),
        (name = "Cart", description = "Shopping cart"),
        (name = "Order", description = "Goods orders"),
        (name = "RunnerOrder", description = "Runner orders"),
        (name = "AdminOrder", description = "Admin goods orders"),
        (name = "AdminRunnerOrder", description = "Admin runner orders"),
        (name = "Category", description = "Category browsing"),
        (name = "Product", description = "Product browsing"),
        (name = "System", description = "System endpoints")
    )
)]
pub struct ApiDoc;
