use utoipa::OpenApi;

use crate::dtos::{
    address_dto, admin_auth_dto, admin_order_dto, admin_runner_order_dto, auth_dto, cart_dto,
    category_dto, config_dto, member_dto, order_dto, product_dto, runner_order_dto, store_dto,
};
use axum_common_api::response::{self, PagedResponse};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Backend Template API",
        version = "1.0.0",
        description = "Minimal user CRUD example"
    ),
    components(
        schemas(
            auth_dto::WechatLoginDto,
            auth_dto::SendSmsCodeDto,
            auth_dto::PhoneSmsLoginDto,
            auth_dto::UserResponse,
            auth_dto::LoginResponse,
            auth_dto::SendSmsCodeResponse,
            config_dto::ConfigResponse,
            config_dto::UpdateConfigRequest,
            address_dto::CreateAddressRequest,
            address_dto::UpdateAddressRequest,
            address_dto::AddressResponse,
            admin_auth_dto::AdminLoginDto,
            admin_auth_dto::AdminResponse,
            admin_auth_dto::AdminLoginResponse,
            member_dto::MemberStatusResponse,
            member_dto::MemberBenefitsResponse,
            store_dto::SelectStoreRequest,
            store_dto::AdminCreateStoreRequest,
            store_dto::AdminUpdateStoreRequest,
            store_dto::StoreNearbyResponse,
            store_dto::StoreResponse,
            store_dto::StoreAdminResponse,
            cart_dto::AddItemRequest,
            cart_dto::UpdateQtyRequest,
            cart_dto::RemoveItemRequest,
            cart_dto::ClearCartRequest,
            cart_dto::CartItemResponse,
            cart_dto::CartResponse,
            order_dto::OrderItemRequest,
            order_dto::PreviewOrderRequest,
            order_dto::OrderPreviewResponse,
            order_dto::CreateOrderRequest,
            order_dto::PayOrderRequest,
            order_dto::CancelOrderRequest,
            order_dto::OrderItemResponse,
            order_dto::OrderResponse,
            runner_order_dto::CreateRunnerOrderRequest,
            runner_order_dto::PayRunnerOrderRequest,
            runner_order_dto::CancelRunnerOrderRequest,
            runner_order_dto::RunnerOrderResponse,
            admin_order_dto::AdminListOrdersQuery,
            admin_runner_order_dto::AdminListRunnerOrdersQuery,
            category_dto::CategoryResponse,
            category_dto::AdminCreateCategoryRequest,
            category_dto::AdminUpdateCategoryRequest,
            product_dto::ProductDetailQuery,
            product_dto::AdminCreateProductRequest,
            product_dto::AdminUpdateProductRequest,
            product_dto::ProductResponse,
            response::ApiResponse<auth_dto::LoginResponse>,
            response::ApiResponse<auth_dto::SendSmsCodeResponse>,
            response::ApiResponse<config_dto::ConfigResponse>,
            response::ApiResponse<Vec<address_dto::AddressResponse>>,
            response::ApiResponse<address_dto::AddressResponse>,
            response::ApiResponse<bool>,
            response::ApiResponse<admin_auth_dto::AdminLoginResponse>,
            response::ApiResponse<Vec<store_dto::StoreAdminResponse>>,
            response::ApiResponse<store_dto::StoreAdminResponse>,
            response::ApiResponse<category_dto::CategoryResponse>,
            response::ApiResponse<product_dto::ProductResponse>,
            response::ApiResponse<member_dto::MemberStatusResponse>,
            response::ApiResponse<member_dto::MemberBenefitsResponse>,
            response::ApiResponse<Vec<store_dto::StoreNearbyResponse>>,
            response::ApiResponse<store_dto::StoreResponse>,
            response::ApiResponse<cart_dto::CartResponse>,
            response::ApiResponse<order_dto::OrderPreviewResponse>,
            response::ApiResponse<order_dto::OrderResponse>,
            response::ApiResponse<Vec<order_dto::OrderResponse>>,
            response::ApiResponse<runner_order_dto::RunnerOrderResponse>,
            response::ApiResponse<Vec<runner_order_dto::RunnerOrderResponse>>,
            response::ApiResponse<Vec<category_dto::CategoryResponse>>,
            response::ApiResponse<PagedResponse<product_dto::ProductResponse>>,
            response::ApiResponse<product_dto::ProductResponse>,
            response::ErrorDetail,
            response::FieldError,
        )
    ),
    tags(
        (name = "Auth", description = "Login and tokens"),
        (name = "Config", description = "Global config"),
        (name = "AdminConfig", description = "Admin global config management"),
        (name = "Address", description = "Address management"),
        (name = "Admin", description = "Admin login"),
        (name = "AdminStore", description = "Admin store management"),
        (name = "AdminCategory", description = "Admin category management"),
        (name = "AdminProduct", description = "Admin product management"),
        (name = "Member", description = "Member status and benefits"),
        (name = "Store", description = "Store browsing"),
        (name = "Cart", description = "Shopping cart"),
        (name = "Order", description = "Goods orders"),
        (name = "RunnerOrder", description = "Runner orders"),
        (name = "AdminOrder", description = "Admin goods orders"),
        (name = "AdminRunnerOrder", description = "Admin runner orders"),
        (name = "Category", description = "Category browsing"),
        (name = "Product", description = "Product browsing"),
        (name = "System", description = "System endpoints")
    )
)]
pub struct SharedApiDoc;
